spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/biblioteca
    username: helio
    password: 12345678
  jpa:
    hibernate:
    #   ddl-auto: validate
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
